### ISSUE TITLE
Cannot Install Plugin in Obsidian

### ISSUE THREAD

**Issue by Vinfall** [abcjs-music/obsidian-plugin-abcjs#24]
I got this when trying to upgrade the plugin today. Tried to uninstall and reinstall, now it cannot even get installed 😞. The console shows this warning, but it does not seem to be informative?

```js
Error: Request failed, status 404
    at new t (app.js:1:699319)
    at Xb (app.js:1:699511)
    at app.js:1:700188
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
(anonymous) @ app.js:1
```

Is it caused by the transition of repos as was mentioned in #23?

**Comment by alensiljak** [comment]
Hi! Thanks for the report. Just fixed this. There was more steps involved in the deployment process than I initially thought. Should be ok now!

The reason was a missing Release with the files attached. I thought they were taken from the repo directly.
In any case, since you know how to get to the console, you can check the call stack and analyze the variables involved. The URL that was used told me what was missing.
It should not happen again since now I know all the steps required.

**Comment by Vinfall** [comment]
>  In any case, since you know how to get to the console, you can check the call stack and analyze the variables involved. The URL that was used told me what was missing.

Oh I was just in a rush to backlog this and did not investigate further, thanks for the tip anyway❤️.
